// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKfnH9G7F-V2P7OCGDjfG2QFgPmQ7DSg',
    appId: '1:144735341433:web:ada37f71f24fb1205e7da8',
    messagingSenderId: '144735341433',
    projectId: 'bus-254ae',
    authDomain: 'bus-254ae.firebaseapp.com',
    storageBucket: 'bus-254ae.appspot.com',
    measurementId: 'G-Z2Y50WJMT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_IEh0bXzcUnTkq0FJTv_4LkYD3mTGQ4',
    appId: '1:144735341433:android:80110b677e909f9e5e7da8',
    messagingSenderId: '144735341433',
    projectId: 'bus-254ae',
    storageBucket: 'bus-254ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUehzgBLgklzCrCTe9zPCVpUuU4JDVXI',
    appId: '1:144735341433:ios:831dcb40c4c0f4445e7da8',
    messagingSenderId: '144735341433',
    projectId: 'bus-254ae',
    storageBucket: 'bus-254ae.appspot.com',
    iosBundleId: 'com.example.busTicketBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUehzgBLgklzCrCTe9zPCVpUuU4JDVXI',
    appId: '1:144735341433:ios:831dcb40c4c0f4445e7da8',
    messagingSenderId: '144735341433',
    projectId: 'bus-254ae',
    storageBucket: 'bus-254ae.appspot.com',
    iosBundleId: 'com.example.busTicketBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKfnH9G7F-V2P7OCGDjfG2QFgPmQ7DSg',
    appId: '1:144735341433:web:69318f825e5e13205e7da8',
    messagingSenderId: '144735341433',
    projectId: 'bus-254ae',
    authDomain: 'bus-254ae.firebaseapp.com',
    storageBucket: 'bus-254ae.appspot.com',
    measurementId: 'G-PCS84V2PDP',
  );
}
